name: 2MS - Secret Scan

on:
  workflow_dispatch:

jobs:
  twoms:
    name: 2MS Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check 2MS version
        run: |
          docker run --rm checkmarx/2ms --version

      - name: Check 2MS help
        run: |
          docker run --rm checkmarx/2ms git --help
